spring:
  application:
    name: peliculaApp
  
  # 1. Configuración de la Base de Datos H2 en memoria
  datasource:
    url: jdbc:h2:mem:cine_db;DB_CLOSE_DELAY=-1;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: 

  # 2. Indicar que ejecute los archivos schema.sql y data.sql automáticamente
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none

  # 3. Habilitar la consola web de H2
  h2:
    console:
      enabled: true
      path: /h2-console